version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bash -c "rm -f ./tmp/pids/server.pid && bin/rails s -b 0.0.0.0 -p 3000"
    environment:
        DATABASE_HOST: db
    ports:
      - '3030:3000'
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    build: ./docker/db
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=ja_JP.UTF-8'
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
volumes:
  bundle:
    driver: local
